var tags = [

    {"key": "App Development", "value": 1},
    {"key": "Software Engineering", "value": 1},
    {"key": "IT Projects", "value": 1},
    {"key": "Full Stack Development", "value": 1},
    {"key": "Algorithms", "value": 1},
    {"key": "Mobile", "value": 1},
    {"key": "Web Applications", "value": 1},
    {"key": "Webservices", "value": 1},
    {"key": "Databases", "value": 1},
    {"key": "Database Tuning", "value": 1},
    {"key": "Sonarqube", "value": 1},
    {"key": "Networks", "value": 1},
    {"key": "Scrum", "value": 1},
    {"key": "Agile Development", "value": 1},
    {"key": "Human Computer Interaction", "value": 1},
    {"key": "Physical Computing", "value": 1},
    {"key": "Joomla", "value": 1},
    {"key": "Jetbrains", "value": 1},
    {"key": "IntelliJ IDEA", "value": 1},
    {"key": "Android Studio", "value": 1},
    {"key": "WebStorm", "value": 1},
    {"key": "Eclipse", "value": 1},
    {"key": "Git", "value": 1},
    {"key": "SVN", "value": 1},
    {"key": "Maven", "value": 1},
    {"key": "Gradle", "value": 1},
    {"key": "MS Visual Studio", "value": 1},
    {"key": "LaTeX", "value": 1},
    {"key": "Adobe CS6", "value": 1},
    {"key": "C", "value": 1},
    {"key": "C++", "value": 1},
    {"key": "C#", "value": 1},
    {"key": "HTML", "value": 1},
    {"key": "HTML5", "value": 1},
    {"key": "CSS", "value": 1},
    {"key": "CSS3", "value": 1},
    {"key": "PHP", "value": 1},
    {"key": "GWT", "value": 1},
    {"key": "Google Web Toolkit", "value": 1},
    {"key": "SAP-ABAP", "value": 1},
    {"key": "jQuery", "value": 1},
    {"key": "JAX-WS", "value": 1},
    {"key": "JAX-RS", "value": 1},
    {"key": "Ajax", "value": 1},
    {"key": "Apache", "value": 1},
    {"key": "Lint", "value": 1},
    {"key": "Jenkins", "value": 1},
    {"key": "Node.js", "value": 1},
    {"key": "MEAN Stack", "value": 1},
    {"key": "XAMPP Stack", "value": 1},
    {"key": "Continuous Integration", "value": 1},
    {"key": "CI", "value": 1},
    {"key": "Continuous Deployment", "value": 1},
    {"key": "CD", "value": 1},
    {"key": "Continuous Delivery", "value": 1},
    {"key": "Responsive Design", "value": 1},
    {"key": "TDD", "value": 1},
    {"key": "Test Driven Development", "value": 1},
    {"key": "Unit Tests", "value": 1},
    {"key": "Integration Tests", "value": 1},
    {"key": "Operating Systems", "value": 1},
    //
    // // OS
    {"key": "Windows", "value": 7},
    {"key": "Unix", "value": 7},
    {"key": "Debian", "value": 7},
    {"key": "Ubuntu", "value": 7},
    {"key": "Android", "value": 7},
    //
    {"key": "Java", "value": 11},
    {"key": "JUnit", "value": 1},
    {"key": "Android", "value": 10},
    {"key": "J2EE", "value": 10},
    {"key": "Spring Framework", "value": 9},
    {"key": "REST", "value": 1},
    {"key": "SOAP", "value": 1},
    {"key": "Javascript", "value": 1},
    {"key": "Jasmine", "value": 1},
    {"key": "JS Unit Tests", "value": 1},
    {"key": "Tomcat", "value": 1},
    {"key": "MongoDB", "value": 1},
    {"key": "PostgreSQL", "value": 1},
    {"key": "MySQL", "value": 1},
    {"key": "SQLite", "value": 1},
    {"key": "Oracle DB", "value": 1},
    {"key": "Arduino", "value": 1},
    {"key": "Gitlab", "value": 1},
    {"key": "Github", "value": 1},
    {"key": "JSP", "value": 1},
    {"key": "Typescript", "value": 1},
    {"key": "Docker", "value": 1},
    {"key": "Express.js", "value": 1},
    {"key": "Grunt", "value": 1},
    {"key": "Slack", "value": 1},
    {"key": "OWASP", "value": 1},

    // general abilities
    {"key": "Scientific Literature", "value": 1},
    {"key": "Product Talks", "value": 1},
    {"key": "Business Talks", "value": 1},
    {"key": "Technical Talks", "value": 1},





    // // HTL
    {"key": "Electrical Engineering", "value": 5},
    {"key": "Networks ", "value": 4},
    {"key": "Energy", "value": 2},
    {"key": "Automation", "value": 2},
    {"key": "Hardware Engineering", "value": 3},
    {"key": "Circuits", "value": 3},
    {"key": "Microcontroller", "value": 3},
    {"key": "Electrical Planning", "value": 1},
    {"key": "Electrical Simulation", "value": 1},
    {"key": "SPS (PLC)", "value": 2},
    {"key": "EPLAN", "value": 2},
    {"key": "NI Multisim", "value": 1},
    {"key": "EAGLE", "value": 1},
    {"key": "S7", "value": 1},
    {"key": "EATON", "value": 1},
    {"key": "CISCO", "value": 1},
    {"key": "Matlab", "value": 3},
    {"key": "Mathcad", "value": 1},
];
